name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests ${{matrix.sdk}} on ${{matrix.os}}
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - uses: actions/checkout@v4
      - run: dart --version
      - run: dart pub get
      - run: dart analyze --fatal-infos .
      - run: dart tool/generate_client.dart
      - run: (cd test && docker compose up --wait)
      - run: dart test
      - run: (cd test && docker compose down --volumes)
      - run: dart tool/prepare_submit.dart
      - name: "check for uncommitted changes"
        run: git diff --exit-code
